/*
 * cf-bcc.h
 *
 * By Ross Ridge
 * Public Domain
 *
 * Sample configuration file for Borland C++ 3.1.
 *
 * @(#) MySC cf-bcc.h 1.2 93/11/10 04:48:36
 *
 */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CONFIG_NO_FORK
#define CONFIG_NO_PIPE
#undef  CONFIG_NO_SPAWN
#undef  CONFIG_NO_DIRECTORY
#define CONFIG_NO_MKTIME
#undef  CONFIG_NO_REMOVE
#undef  CONFIG_NO_RENAME
#undef  CONFIG_NO_STRERROR
#undef  CONFIG_NO_STRSTR
#undef  CONFIG_NO_TIMEZONE_VAR
#undef  CONFIG_NO__CHMOD
#define CONFIG_NO_FSYNC

#undef  CONFIG_USE_DIFFTIME

#undef  CONFIG_DECLARE_ERRNO
#undef  CONFIG_DECLARE_STRERROR
#undef  CONFIG_DECLARE_MALLOC
#undef  CONFIG_DECLARE_STAT
#undef  CONFIG_DECLARE_GETPWUID
#undef  CONFIG_DECLARE_GETLOGIN
#define CONFIG_DECLARE_TIMEZONE
#define CONFIG_DECLARE_TZSET
#define CONFIG_DECLARE_FDOPEN

#undef  CONFIG_INCLUDE_SYS_TYPES_H
#define CONFIG_INCLUDE_FCNTL_H
#undef  CONFIG_INCLUDE_SYS_FILE_H
#undef  CONFIG_INCLUDE_UNISTD_H
#undef  CONFIG_INCLUDE_PROTOTYPES_H
#undef  CONFIG_INCLUDE_SYS_WAIT_H
#define CONFIG_INCLUDE_IO_H
#define CONFIG_INCLUDE_PROCESS_H

#undef  CONFIG_WAIT_IS_A_USELESS_MACRO

#undef  CONFIG_SAVED_SETUID
#undef  CONFIG_SETREUID

#define CONFIG_DIFF_COMMAND	"diff"
#undef  CONFIG_DIFF_SWITCHES

#undef  CONFIG_COMPLETE_TEMPLATES

#undef  CONFIG_UIDS
#define	CONFIG_BINARY_FILE
#define CONFIG_MSDOS_FILES
#define CONFIG_SYNC_BEFORE_REOPEN
#define CONFIG_BORLANDC
#undef  CONFIG_DJGPP
#define CONFIG_NO_ABORT
#undef  CONFIG_TEMP_DIRECTORY
#define CONFIG_EOL_CHARACTER		'\n'

#define CONFIG_LINEBUF_CHUNK_SIZE	256
#define CONFIG_LIST_CHUNK_SIZE		8

#define CONFIG_FILE_NAME_GUESSING
#define CONFIG_USE_ARCHIVE_BIT
#undef  CONFIG_WHAT_USE_STDIO

#endif /* __CONFIG_H__ */

/* Local variables: */
/* mode: c++ */
/* End: */
