/*
 * cf-sls.h
 *
 * By Ross Ridge
 * Public Domain
 *
 * Sample MySC configuration file for use with SLS (1.02) Linux.
 * Other Linux distributions may differ.
 *
 * @(#) MySC cf-sls.h 1.2 93/11/10 04:48:36
 *
 */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#undef  CONFIG_NO_FORK
#undef  CONFIG_NO_PIPE
#undef  CONFIG_NO_SPAWN
#undef  CONFIG_NO_DIRECTORY
#undef  CONFIG_NO_MKTIME
#undef  CONFIG_NO_REMOVE
#undef  CONFIG_NO_RENAME
#undef  CONFIG_NO_STRERROR
#undef  CONFIG_NO_STRSTR
#define CONFIG_NO_TIMEZONE_VAR


#undef  CONFIG_DECLARE_ERRNO
#undef  CONFIG_DECLARE_STRERROR
#undef  CONFIG_DECLARE_MALLOC
#undef  CONFIG_DECLARE_STAT
#undef  CONFIG_DECLARE_GETPWUID
#undef  CONFIG_DECLARE_GETLOGIN
#undef  CONFIG_DECLARE_TIMEZONE
#undef  CONFIG_DECLARE_TZSET
#undef  CONFIG_DECLARE_FDOPEN

#undef  CONFIG_INCLUDE_SYS_TYPES_H
#define CONFIG_INCLUDE_FCNTL_H
#undef  CONFIG_INCLUDE_SYS_FILE_H
#define CONFIG_INCLUDE_UNISTD_H
#define CONFIG_INCLUDE_SYS_WAIT_H
#undef  CONFIG_INCLUDE_PROTOTYPES_H
#undef  CONFIG_INCLUDE_IO_H
#undef  CONFIG_INCLUDE_PROCESS_H

#define CONFIG_WAIT_IS_A_USELESS_MACRO

#undef  CONFIG_SAVED_SETUID
#define CONFIG_SETREUID

#define CONFIG_DIFF_COMMAND	"/usr/bin/diff"
#undef  CONFIG_DIFF_SWITCHES

#define CONFIG_COMPLETE_TEMPLATES

#define CONFIG_UIDS
#undef	CONFIG_BINARY_FILE
#undef  CONFIG_MSDOS_FILES
#undef  CONFIG_BORLANDC
#define CONFIG_DJGPP
#undef  CONFIG_NO_ABORT
#define CONFIG_EOL_CHARACTER		'\n'

#define CONFIG_LINEBUF_CHUNK_SIZE	1024
#define CONFIG_LIST_CHUNK_SIZE		16

#define CONFIG_FILE_NAME_GUESSING
#undef  CONFIG_USE_ARCHIVE_BIT

#endif /* __CONFIG_H__ */

/* Local variables: */
/* mode: c++ */
/* End: */

