/*
 * cf-xenix.h
 *
 * By Ross Ridge
 * Public Domain
 *
 * Sample MySC configuration file for use with SCO Xenix.
 *
 * @(#) MySC cf-xenix.h 1.1 93/11/09 17:17:46
 *
 */
 
#ifndef __CONFIG_H__
#define __CONFIG_H__

#undef  CONFIG_NO_FORK
#undef  CONFIG_NO_PIPE
#undef  CONFIG_NO_SPAWN
#undef  CONFIG_NO_DIRECTORY
#define CONFIG_NO_MKTIME
#define CONFIG_NO_REMOVE
#define CONFIG_NO_RENAME
#define CONFIG_NO_STRERROR
#define CONFIG_NO_STRSTR
#undef  CONFIG_NO_TIMEZONE_VAR

#undef  CONFIG_DECLARE_ERRNO
#undef  CONFIG_DECLARE_STRERROR
#undef  CONFIG_DECLARE_MALLOC
#define CONFIG_DECLARE_STAT
#undef  CONFIG_DECLARE_GETPWUID
#define CONFIG_DECLARE_GETLOGIN
#undef  CONFIG_DECLARE_TIMEZONE
#undef  CONFIG_DECLARE_TZSET
#undef  CONFIG_DECLARE_FDOPEN

#define CONFIG_INCLUDE_SYS_TYPES_H
#define CONFIG_INCLUDE_FCNTL_H
#undef  CONFIG_INCLUDE_SYS_FILE_H
#undef  CONFIG_INCLUDE_UNISTD_H
#define CONFIG_INCLUDE_PROTOTYPES_H
#undef  CONFIG_INCLUDE_IO_H
#undef  CONFIG_INCLUDE_PROCESS_H

#undef  CONFIG_SAVED_SETUID
#undef  CONFIG_SETREUID

#define CONFIG_DIFF_COMMAND	"/bin/diff"
#undef  CONFIG_DIFF_SWITCHES

#define CONFIG_COMPLETE_TEMPLATES

#define CONFIG_FILE_NAME_GUESSING

#define CONFIG_UIDS
#undef	CONFIG_BINARY_FILE
#undef  CONFIG_MSDOS_FILES
#undef  CONFIG_BORLANDC
#undef  CONFIG_DJGPP
#define CONFIG_EOL_CHARACTER		'\n'

#define CONFIG_LINEBUF_CHUNK_SIZE	1024
#define CONFIG_LIST_CHUNK_SIZE		16

#endif /* __CONFIG_H__ */

/* Local variables: */
/* mode: c++ */
/* End: */

